### ISSUE TITLE
Consider linting of coffee files

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#157]
It's strange that we lint `.js`, but not `.coffee` files.

Solution: https://github.com/vojtajina/grunt-coffeelint

Otherwise coffee should be replaced with pure js.

**Comment by mrhyde** [comment]
We should replace it... Coffee is lagging behind JS at this moment and there are no objective reasons to keep it (except cleaner syntax)

**Comment by ArmorDarks** [comment]
Well, the cleaner syntax (especially for Objects) is the only reason I use it at all.

At some point I thought it's abbadon ware, but they suddenly made few quite massive releaseds in December and January, http://coffeescript.org/. So, at least it's not dead.

**Comment by mrhyde** [comment]
Still, most of the actually useful stuff comes from ES6 and babel. We should get rid of it during this year.

**Comment by ArmorDarks** [comment]
Well, process of transition is quite straightforward with https://github.com/decaffeinate/decaffeinate and can be done fairly quickly.

My only concern is representation of configuration objects. In plan JS they will look much worse.

**Comment by ArmorDarks** [comment]
So, seems like we're going to get rid of CoffeeScript in next versions, so I'm closing this.
