### ISSUE TITLE
Consider making `jspm install` part of npm install

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#163]
I saw some apps installing jspm with npm `postinstall` hook in package.json.

Maybe we should do same thing? It seems to be kind of overkill to install all dependencies with each `grunt default`...

**Comment by mrhyde** [comment]
JSPM integration in Kotsu is far from perfect but I'm not sure what problem it will solve since for CI builds it literally have no impact and during development, you might want to reset/reinstall jspm modules. I would say we need more tests on this topic.

**Comment by ArmorDarks** [comment]
I think it's more related to the fact how logically it should be treated. Sometimes I get weird feeling when I launch `grunt default`, look into console and wonder, why the hell I'm re-downloading and installing all JSPM dependencies each time I launch dev environment? Maybe sometimes that's not what I want to do.

JSPM seems to be quite similar in concept to NPM and in NPM we don't pull dependencies unless we explicitly asked for it.

**Comment by mrhyde** [comment]
Nice point. I will think about it.

**Comment by mrhyde** [comment]
I think we should treat jspm modules just like npm's. So we want to install the once during install process for finished projects and for projects in development install them one by one but still - just once.
