### ISSUE TITLE
Replace `grunt-standard` with `standard`

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#174]
[grunt-standard](https://github.com/pdehaan/grunt-standard) seems to be mostly unmaintained considering some issues, which weren't resolved for months (see https://github.com/pdehaan/grunt-standard/issues/11).

Besides, it makes something strange with standard ESLint rules, so they becoming inaccessible for Sublime Text SublimeLinter SublimeLinter-contrib-Standard plugin (wow, that was long name...). It results in SublimeLinter crashing or reporting numerous fake errors.

And maybe there is little reason to keep extra layer between Standard, Stylelint and Grunt, while we don't do anything like that for Jest...

**Comment by mrhyde** [comment]
The whole point was that in one of the versions of standard they split formater into a separate module and this grunt plugin had them both. But looking on this matter now I think that having standard as a separate module would not hurt since it doesn't take part in a build process.

**Comment by ArmorDarks** [comment]
I'm still confused how to use commands properly... back in time we added `grunt-standard` and `grunt-stylelint` 

1. To be callable completely through Grunt
2. To pass all paths via Grunt methods (which was impossible with `npm run`

But now we have _again_ module, which called through `npm run` (or `grunt-shell`) which breaks whole pattern...

Just as a side note, for `Jest` it's mostly recommended to call it via `npm run`, or `grunt-run`, or `grun-shell`, see https://github.com/leebyron/grunt-jest.

**Comment by mrhyde** [comment]
Well, I would say that it looks like we should get rid of `grunt` during this year and `standard` is quite fast to locate js files even without specifying a path to it. As a part of the migration process, it's a painful change and we will have more control on actual module version ditching the intermedium.
