### ISSUE TITLE
Fix `url-join` bugs

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#176]
We recently added [url-join](https://github.com/jfromaniello/url-join/) for Nunjucks.

It's great little library and can handle complex urls.

Unfortunately, there are some issues, which should be resolved. Mostly they don't do as much harm, except few ones, but I will list them all just to remember:

https://github.com/jfromaniello/url-join/issues/20
https://github.com/jfromaniello/url-join/issues/21
https://github.com/jfromaniello/url-join/issues/18
https://github.com/jfromaniello/url-join/issues/10
https://github.com/jfromaniello/url-join/issues/6
https://github.com/jfromaniello/url-join/pull/19

For instance, it will not work with our most common scenarios due to bug with double `//`:

``` jinja
href='{{ localeDir() }}{{ url }}'
```

because

``` js
urljoin(localeDir(), url)
```

will produce wrong `//some/url/goes/here` if original url contains leading `/`, like `/some/url/goes/here`

It doesn't matter if `localeDir()` returns here for base locale `/`, or `''`. Join will always wrongly convert everything into relative protocol.

**Comment by mrhyde** [comment]
We should look for something that is similar to node [URL](https://nodejs.org/api/url.html#url_url_resolve_from_to) module

**Comment by mrhyde** [comment]
After taking a look at source code of that library I think we definitely should look for something better or implement our own module since it's quite trivial.

**Comment by ArmorDarks** [comment]
Node's URL resolve and it's browser-side implementations doing different thing — it _resolves_ urls to final state. It's completely different task.

Unfortunately all other libraries have much less features or incomplete, I didn't find good alternatives. Besides, this one is the most popular (see NPM stats). Let's see will author reply, I want first to know how alive this library.

**Comment by ArmorDarks** [comment]
@StyleT

Just for the information, we opted to use more reliable  [`URI.js`](https://medialize.github.io/URI.js/) instead of [`url-join`](https://github.com/jfromaniello/url-join).

Not everything perfect with it too, but we've augmented it slightly [here](https://github.com/LotusTM/Kotsu/blob/master/modules/urljoin.js) to achieve some desired functionality and fix some (supposedly) not correct behavior. And some [tests](https://github.com/LotusTM/Kotsu/blob/master/tests/kotsu/urljoin.test.js) just to showcase of augmented behavior.
