### ISSUE TITLE
Consider removing of `source` directory

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#256]
Current structure can be seen here: https://github.com/LotusTM/Kotsu/wiki/Structure

Those days I'm finding myself thinking that additional nesting level, introduced by `source` directory seems more and more redundant. Thus, we can consider removing `source` directory, which will result in following structure:

```
Kotsu
├─ build
├─ data
├─ fonts
├─ icons
├─ images
├─ jspm_packages
├─ locales
├─ modules
├─ node_modules
├─ scripts
├─ sprites
├─ static
├─ styles
├─ tasks
├─ temp
├─ templates
├─ tests
└─ ...configuration files...
```

![explorer_2017-07-05_22-46-00](https://user-images.githubusercontent.com/4460311/27882047-c61f0a10-61d3-11e7-90f2-1b5330640216.png)

**Comment by mrhyde** [comment]
Before:
 - this is build folder
 - this is temp folder
 - this is source folder
 - and those are folders for modules

After: 
 - here is your bowl of shit-soup

![](http://i.imgur.com/JisGdqD.jpg)

**Comment by mrhyde** [comment]
Just a reminder why we have introduced `source` folder in a first place - is to define what user can edit and what he should not. Removing this folder will complicate things too much without giving real benefits.

**Comment by ArmorDarks** [comment]
(╯°□°）╯︵ ┻━┻
