### ISSUE TITLE
Consider UPPER_CASE for root data properties

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#258]
Right now our data index looks something like:

```coffee
  data =
    path:
      fonts: config('path.build.fonts').replace(buildRoot, '')
      images: imagesPath
      scripts: config('path.build.scripts').replace(buildRoot, '')
      styles: config('path.build.styles').replace(buildRoot, '')
      sprites: config('path.build.sprites').replace(buildRoot, '')
      source: '<%= path.source %>'
      build: '<%= path.build %>'
    site:
      name: pkg.name
      version: pkg.version
      description: pkg.description
      homepage: if sitename then "https://#{sitename}" else pkg.homepage
      viewport: 'width=device-width, initial-scale=1'
      themeColor: '#a593e0'
      locales: config('locales')
      baseLocale: config('baseLocale')
      googleAnalyticsId: false # 'UA-XXXXX-X'
      yandexMetrikaId: false # 'XXXXXX'
    pageDefaults:
      image: ''
      class: ''
      bodyClass: ''
      applyWrapper: true
      showContentTitle: true
      showBreadcrumb: true
      showSidebar: false
    social:
      # Add any other social services following same pattern
      twitter:
        handle: pkg.twitter
        image: imagesPath + '/twitter.png'
        url: "https://twitter.com/#{pkg.twitter}"
      facebook:
        image: imagesPath + '/facebook.png'
        url: 'https://www.facebook.com/Lotus-TM-647393298791066/'
    env:
      production: '<%= env.production %>'
      staging: '<%= env.staging %>'
      build: '<%= env.build %>'
      hotModuleRloading: '<%= env.hotModuleRloading %>'
    data:
      currentYear: new Date().getFullYear()
```

we can capitilize root properties, since they all seems to be very close to constants:

```coffee
  data =
    PATH:
      fonts: config('path.build.fonts').replace(buildRoot, '')
      images: imagesPath
      scripts: config('path.build.scripts').replace(buildRoot, '')
      styles: config('path.build.styles').replace(buildRoot, '')
      sprites: config('path.build.sprites').replace(buildRoot, '')
      source: '<%= path.source %>'
      build: '<%= path.build %>'
    SITE:
      name: pkg.name
      version: pkg.version
      description: pkg.description
      homepage: if sitename then "https://#{sitename}" else pkg.homepage
      viewport: 'width=device-width, initial-scale=1'
      themeColor: '#a593e0'
      locales: config('locales')
      baseLocale: config('baseLocale')
      googleAnalyticsId: false # 'UA-XXXXX-X'
      yandexMetrikaId: false # 'XXXXXX'
    PAGE_DEFAULTS:
      image: ''
      class: ''
      bodyClass: ''
      applyWrapper: true
      showContentTitle: true
      showBreadcrumb: true
      showSidebar: false
    SOCIAL:
      # Add any other social services following same pattern
      twitter:
        handle: pkg.twitter
        image: imagesPath + '/twitter.png'
        url: "https://twitter.com/#{pkg.twitter}"
      facebook:
        image: imagesPath + '/facebook.png'
        url: 'https://www.facebook.com/Lotus-TM-647393298791066/'
    ENV:
      production: '<%= env.production %>'
      staging: '<%= env.staging %>'
      build: '<%= env.build %>'
      hotModuleRloading: '<%= env.hotModuleRloading %>'
    DATA:
      currentYear: new Date().getFullYear()
```

This means, that templates will call capitalized version instead of regular one.

![sublime_text_2017-07-06_20-12-48](https://user-images.githubusercontent.com/4460311/27923573-836569e4-6287-11e7-9db4-8a1b2005f92d.png)

I'm not sold completely on it yet. From one side, those values indeed are more like a constants, besides making them capital effectively encapsulates them from regular variables (as in JS, you can have both `path` and `PATH` variables, and they will reference different values), and means that you can place into root even relatively not-named-safely properties, like `DATA` or `SOCIAL`.

But from other side output in Nunjucks becomes a bit wonky, and making properties of data object (not real standalone variables) capitalized constants feels a bit wrong. Not to mention that values for those properties can be reassigned through Front Matter or `config()` (though, not recommended), thus they aren't real constants.

Besides, it is yet a question, should `page` be capitalized, since it's values can be assigned from page's Front Matter and it serves like `this`, and `this` in JS isn't capitalized.

**Comment by mrhyde** [comment]
I can see the reasoning behind this, but facing the same doubts as you do...
Moving it to backlog for now

**Comment by ArmorDarks** [comment]
Another, less head-bashing approach is to capitalize root variables, like `Site`, `Data`, etc.

But this makes it inconsistent with JavaScript, where capitalized usually only classes, while here we obviously don't have classes.

Ouch, and, btw, capitalization will make it collide with Nunjucks components (macros). Definitely not an option.

**Comment by mrhyde** [comment]
I think constant-a-like variables are more reasonable approach since it will indicate that redefining this variable it something that we do not recommend. Also, we can clearly separate Kotsu global variables and user defined ones.
