### ISSUE TITLE
manifest.json

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#270]
Someone and somehow completely unexpectedly added `manifest.json` to the project without any proper research... Who could it be?

I intentionally avoided adding it directly to Kotsu, since few things around configuration it wasn't that clear and didn't fit well into available within Kotsu data.

That should be fixed.

**Comment by mrhyde** [comment]
Probably some jackass... But since no harm was done we should improve situation a little and move it from `static`  to `templates` and pass some data to it for sake of better world

**Comment by ArmorDarks** [comment]
We would never know name of the hero...

As a side note, we do not add `lang` property right know, because right now it is unclear how it should be handled for multilanguage site — should manifest be placed into each locale, or not? There are some proposals in specs and it can change in future. Since it isn't used anywhere as of right now, we will wait until stable and reliable practice will appear.
