### ISSUE TITLE
Fix AppVeyor

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#289]
We have to do something with it.

All those errors are quite annoying: 

![chrome_2017-08-11_12-26-48](https://user-images.githubusercontent.com/4460311/29207864-63c60038-7e90-11e7-8edd-e2b446208203.png)

**Comment by mrhyde** [comment]
Fixed in db203834b5a2eef49089ed729c671a40469c6ded

**Comment by mrhyde** [comment]
Also disabled appveyor for branches such as PRs since it's impossible to handle lockfile changes for now

**Comment by ArmorDarks** [comment]
Kinda-stupid possible fix for Appveyor not living well with lock file is `npm config set package-lock false` command.

**Comment by mrhyde** [comment]
Looks like a better alternative.

**Comment by ArmorDarks** [comment]
Seems to work. Nice!

**Comment by ArmorDarks** [comment]
Seems that using `npm install -g npm@latest` _both_ in AppVeyor config and in development environment alongside with https://github.com/LotusTM/Kotsu/pull/315 fixed the issue, so `package-lock.json` in AppVeyor has been enabled again.
