### ISSUE TITLE
Update dockerfile

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#290]
In one of our commercial projects dockerfile and circle.yml looks like this:

```diff
  FROM lotustm/nginx

  ENV SITENAME $SITENAME

- ADD ./build /var/domains/$SITENAME/www
+ COPY build /var/domains/$SITENAME/www
+ COPY docker/nginx /etc/nginx
  RUN sed -i "s/example.com/$SITENAME/g" /etc/nginx/sites-enabled/default.conf
```

```diff
machine:
  node:
    version: 8

checkout:
  post:
    - git submodule update --init --recursive

test:
  post:
    - npm run build

deployment:
  production:
    branch: master
    commands:
      - ssh-keyscan $SERVER_IP > ~/.ssh/known_hosts
      - cat dockerfile.template | envsubst > dockerfile
-     - tar cvzf app.tgz dockerfile build/
+     - tar cvzf app.tgz dockerfile build/ docker/
      - scp app.tgz core@$SERVER_IP:~/$CIRCLE_PROJECT_REPONAME.tgz
      - scp deploy.sh core@$SERVER_IP:~/deploy.sh
      - ssh core@$SERVER_IP chmod +x deploy.sh
      - ssh core@$SERVER_IP ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1
```

I guess this is related to ability to override containers content. I think we should integrate those configs into Kotsu. @mrhyde  What do you think?

Kotsu won't have any overrides, but will be prepared for them. I will write then short documentation on how to override.

**Comment by mrhyde** [comment]
I didn't add those changes to Kotsu because this is common docker process and I'm not sure if we should point that out explicitly. Basically you can override not only `nginx` related files but any files of any layer up to the top.

**Comment by ArmorDarks** [comment]
I just don't see why not make it already completely prepared part of Kotsu, so that you won't need to change anything when adding overrides.

**Comment by mrhyde** [comment]
Since we are using it in only one project I think this should be just documented as available feature without polluting workspace

**Comment by ArmorDarks** [comment]
Once again I do not understand why not to add it as constant part of Kotsu? Are there any issues with that?

I think it is more convenient just add `docker` folder without any additional setup. Besides, the less discrepancies between side projects and Kotsu main build, the easier to update those side projects with latest Kotsu builds.

**Comment by mrhyde** [comment]
You can't add empty folders to `git`

**Comment by ArmorDarks** [comment]
Well, we can (`.gitkeep`), but I didn't mean to.

I proposed solely to add defined above changed to dockerfile and circle config.

Or it will error on non-existing `docker` directory?

**Comment by mrhyde** [comment]
Have no idea and can't test it on Windows machine.
Furthermore, this will only work with our container and move all workflow to even more monolithic and closed environment. I personally would prefer to see other people to implement their own things on top of Kotsu and use it just as a base layer.

**Comment by mrhyde** [comment]
I'm closing this because at this moment there is nothing else we can or should add to our docker configuration.
