### ISSUE TITLE
Remove uglify JS

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#294]
JSPM runs it under the hood with ` --minify` flag, so it seems to be no longer needed.

Drop it?

**Comment by mrhyde** [comment]
Yeah, but we need to see that version and with what flags... I don't think that we will get the same level of flexibility

**Comment by mrhyde** [comment]
At this moment `jspm` is using uglifyjs@2 and `grunt-contgib-uglify` - uglifyjs@3, but despite that the compression rate looks the same.
Taking in consideration how JS community grows and evolved I would say that that a new prominent project will emerge before `jspm` updates to uglifyjs@3 or even better - [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony)

**Comment by ArmorDarks** [comment]
Supressed by 77f1c7605ba5bf5dfe1ecb6d146081f8940e16dd
