### ISSUE TITLE
Move Wiki to main repository

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#317]
Well, it turned out that Wiki itself isn't that handy, because documentation becomes very detached from commits in main repository.

As already has been discussed, we have to move it into main repository and commit to documentation alongside with code changes and changelog updates. It will make even commits more transparent.

We have few options:

1. Move it to website, into `Docs` section.

   That was my initial plan. Unfortunately, it isn't that wise. Kotsu comes with minimum of styles, and we do not want to add more opinionated predefined one to make starting fresh projects easier, docs looks quite... dull.

2. Move docs as `.md` files into `docs` directory.

   They won't be available on website (or we can place a link there), but will be much more readable.

   I think right now it is better way to go.

We can revisit this when we will end up with separate Kotsu website. But as for know I'd like to avoid maintaining this repository alongside with additional project, which will require constant updates from main repo.

**Comment by ArmorDarks** [comment]
Moved to `docs` directory in https://github.com/LotusTM/Kotsu/commit/65090d1bfeb601ad418c3e978fef0f1c173fc537

**Comment by mrhyde** [comment]
Since this was the only affordable solution at this moment, I'm going to close this issue
