### ISSUE TITLE
Fix failing Greenkeeper tests and `package-lockfile.json`

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#350]
Constantly failing Greenkeeper tests due to modified files checks and always modified `package-lockfile.json` starts to be really annoying.

It becomes even worse, when the user uses NPM older than the one used in the CI tools, since `package-lockfile.json`  in some version has a different order and that results in different output after `npm install`.

Right now there are two ways to fix this:

1. Use official package [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile).

   Downsides:

   1. Additional dependency
   2. Requires Github API token setup on CI-side, which makes init of Kotsu longer...
   3. Supports limited amount of CI tools

2. Ignore `package-lock.json` changes during modified files tests if the current environment is Greenkeeper.

   This is easily done [that way](https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/upload.js#L14), by checking `env` properties which CI tools exposing.

   Downsides:

   1. That will pass sometimes possible discrepancies caused by different NPM versions in lockfile
   2. Will supports limited amount of CI tools too, because it requires to know which `env` property to check

**Comment by mrhyde** [comment]
We decided to go with `greenkeeper-lockfile` solution and implemented in on top of Circle CI. See 272ae1bde9ede1b43754e70376c15df0c4937e3c

**Comment by ArmorDarks** [comment]
We still need to do similar thing for other CI configs

**Comment by mrhyde** [comment]
No, we don't.
