### ISSUE TITLE
Option to generate pages in root and `baseLocale` dirs

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#53]
We need option to generate same pages in root and in `baseLocale` dirs in same time.

For pages in root should be set canonical url, which should lead to same page in `baseLocale`

Otherwise we'll have to use server-side redirect. So far it seems to be most logical workaround

**Comment by ArmorDarks** [comment]
@mrhyde Do we still want to do this? What do you think?

I remember it was your request.

**Comment by ArmorDarks** [comment]
Can you remind me why we can't use for this already existing content at root `/`? Why for base locale (let's say, `en-US`) we need to have and `/` and `/en-US/`?

**Comment by mrhyde** [comment]
Nope...

**Comment by ArmorDarks** [comment]
:D

**Comment by mrhyde** [comment]
I have tried :man_shrugging:

**Comment by ArmorDarks** [comment]
`baseLocaleAsRoot` option is removed from Kotsu 1.7.0, and this issue no longer relevant with it.

Now it is possible to use locales urls to specify where pages should end up:

```diff
locales:
  'en-US':
    locale: 'en-US'
+   url: '/'
```

If you want same locale to show up in few directories, I guess we can make `url` to be array or something, but it will complicate other things.

Alternatively, it is possible to create another same locale, which will put thing into different directory.

However, all this is _unrecommended_, since will lead to content duplication. It can be avoided by using canonical urls, but still, it is much more preferable to use redirects, which is now a breeze to configure with latests additions to Kotsu overriding of Docker Nginx directives.
