### ISSUE TITLE
Automate installation of submodules

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#55]
Ekzo.sass should be installed and attached as submodule after `npm install`.

Not sure is it possible, but theoretically — yes. Probably we can use post-install script, which will install git submodule if there is no certain submodule yet.

Please, note that current issue related to initial installation only. Updating of submodule should be made with usual git methods, not via `npm install`. Probably.

Some more information about this: https://github.com/npm/npm/issues/6700

**Comment by ArmorDarks** [comment]
Turns out `npm install` pulls releases, which already have downloaded submodules, though, they aren't initialized, you need to re-init them manually.

**Comment by mrhyde** [comment]
We should consider creating separate `kotsu-cli` package that will manage `kotsu` package as dependency and install it in user defined folder correctly
