### ISSUE TITLE
Consider change of license to Apache 2.0

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#58]
I'm really starting to doubt that licensing Kotsu under MIT is good thing, because in many ways it's _way too permissive_.

I'd consider Apache 2.0 license.

Some info:

* https://news.ycombinator.com/item?id=3402450
* https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license

**Comment by mrhyde** [comment]
After evaluating available [choices](http://choosealicense.com/licenses/) Apache 2.0 license looks as an ideal candidate

**Comment by mrhyde** [comment]
More reading on the matter:
https://lukasa.co.uk/2012/05/GPL_vs_MIT_Which_License_To_Use/
https://www.chef.io/blog/2009/08/11/why-we-chose-the-apache-license/
