### ISSUE TITLE
Google Analytics and Yandex.Metrics ids

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#70]
Those settings probably have to be elevated to data or gruntfile:

![sublime_text_2016-08-24_22-00-31](https://cloud.githubusercontent.com/assets/4460311/17943946/3efd28da-6a46-11e6-8b05-2de21c790718.png)

**Comment by mrhyde** [comment]
This should definitely be in global config file (top layer of data source)
