### ISSUE TITLE
Referencing of sitemap.xml

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#88]
Current implementation with `<link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml">` seems to be not working.

Waiting for feedback from https://github.com/h5bp/html5-boilerplate/issues/1895.

**Comment by ArmorDarks** [comment]
Well, strangely enough that didn't have any effect :(

**Comment by mrhyde** [comment]
After hours of research, there is literally not a single credible source to back up this method and all search engines suggest using robots.txt directive (see related PR on h5bp)

**Comment by ArmorDarks** [comment]
Yeah, but we added it to `robots.txt` and didn't have any effect too, despite Google declares it in their `robots.txt` https://www.google.com.ua/robots.txt

**Comment by mrhyde** [comment]
I think that section is used to display only sitemaps uploaded by user.
